### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by leowzukw** [samoht/alcotest#10]
It would be great to have a set of exemple to start easier.

Maybe a bunch of files in an `example` folder.

I never used alcotest but I thinks on something like this : 

``` ocaml
(* Define some function to test *)
(* The code *)

(* Define the tests *)
(* The code *)

(* Run the tests *)
```

**Comment by samoht** [comment]
Yes I was planning these for a long time, I'll do it soon. You can see a good example there: https://github.com/mirage/mirage-fs-unix/blob/master/lib_test/test_fs_unix.ml#L386

**Comment by leowzukw** [comment]
Thanks!

**Comment by leowzukw** [comment]
I created a simple file to try alcotest.

I posted it on [Gist](https://gist.github.com/leowzukw/33b7920ddfc35246980f), you may use it if you want.

**Comment by samoht** [comment]
Thanks, I've added it to the repository.

**Comment by leowzukw** [comment]
I'm glad to help the project, it find alcotest beautiful and easy to use.
